### ISSUE TITLE
Best practice handling type conversion

### ISSUE THREAD

**Issue by michshat** [calmm-js/kefir.react.native#2]
What would be the best practice converting type from integer to string (or any other type). For instance ReactNative's `TextInput` expects `string` value. If a property of the model is `numeric`, should the conversion be done at the meta level via transform or inline in the control:

```
<K.TextInput
                value={K(item.view(M.SUM.a), value => value.toString())}
                onChangeText={text => item.lens(M.SUM.a).set(text)}
              />
```

**Comment by polytypic** [comment]
First of all I would recommend keeping the model state consistent.  If something in the model should be a number, then keep it that way.

Instead of just using a plain `TextInput` you probably want to create input controls that, for example, only allow the user to enter valid input or give feedback when input is incorrect and do not update the model unless the input is correct.  For a number input, in particular, consider that mobile devices often have a special numeric input component and if you want users to enter numbers, you should use that.

I wrote a toy example of a [restricted-input](https://github.com/calmm-js/kral-examples/blob/master/src/restricted-input.js) component and used it in two slightly different ways in [here](https://github.com/calmm-js/kral-examples/blob/master/src/scroll.js#L51-L52).

If some relatively simple logic is done only for presentation purposes (affecting the visual aspects of a control) then I don't see much harm in doing that inside the control.  However, one problem with putting complex logic inside controls is that such code is difficult to test.  Moving code outside of controls (and observables) and into separate functions tends to make the code easier to test.

**Comment by michshat** [comment]
Thank you for the overview and the sample. I used that as a guide and here is what it looks like - seem to work as expected. Check it out:

``` jsx
export const NumberInput = ({value, ...props}) => {  
  const edited = Atom()  
  const shown = K(value, edited, (value, edited) => 
    edited === undefined ? value.toString() : edited)                  
  const validationStyle =  K(shown, shown => 
    number.parse(shown) ? [props.style, styles['success']] : [props.style, styles['error']])

  return  <K.TextInput {...props} 
      value={shown}
      style={validationStyle}
      onChangeText={text => {                                        
                    if (number.parse(text)) {                                           
                      value.set(parseFloat(text))                                          
                    } 
                    edited.set(text)                     
                  }}  
    />
}

export const number = {  
  parse: text => {    
    return !isNaN(text) && isFinite(text)
  }
}
```

``` jsx
<NumberInput 
                style={{height: 40, borderColor: 'gray', borderWidth: 1}}            
                value={item.lens(M.SUM.b)}                           
              /> 
```

``` js
export const mock = {a: 0, b: 0}

export const SUM = {
  augment: L.augment({
    c: ({a, b}) => R.add(a, b),
    error: ({a, b}) => R.equals(a, 3) ? 'error' : 'success'    
  }), 
  error: "error",
  c: "c",
  a: "a",
  b: "b"  
}
```

![vid1](https://cloud.githubusercontent.com/assets/13825309/15629987/d689f272-24f6-11e6-9e30-8c074d999271.gif)
